version: '2'
services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress_a_brosy_com
    expose:
      - 80
    depends_on:
      - db
    volumes:
      - ~/stack/abrosycom_wordpress-data:/wordpress-data
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    links:
      - db:mysql
    environment:
      VIRTUAL_HOST: "manage.brosy.com"
      VIRTUAL_PORT: "80"
      LETSENCRYPT_HOST: "manage.brosy.com"
      LETSENCRYPT_EMAIL: security@brosy.com"
#      WORDPRESS_DB_NAME: "wordpress"
      WORDPRESS_DB_HOST: "db"
      WORDPRESS_TABLE_PREFIX: "wp_"
      WORDPRESS_DB_PASSWORD: "Pa55w0rd"
  db:
    image: "mariadb"
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "Pa55w0rd" 

networks:
  default:
    external:
      name: nginx_proxy

volumes:
  db_data:
