version: '2'
services:
  portainer:
    restart: always
    image: portainer/portainer
    container_name: portainer
    command: --templates http://templates/templates.json
    ports:
      - 9000:9000
    networks:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/stack/portainer/data:/data
    environment:
      VIRTUAL_HOST: hosted.brosy.com

  templates:
    image: portainer/templates
    container_name: "portainer-templates"
    networks:
      - backend

  watchtower:
    image: centurylink/watchtower
    container_name: "portainer-watchtower"
    command: --cleanup portainer-app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  backend:
    driver: bridge
